name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  database: postgres
  user: postgres
  password2: postgres

  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}

  language: ${{ vars.LANGUAGE }}
  developer: ${{ vars.DESARROLLADOR }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Mostrar imagnes"
      run: |
        echo "Imagenes disponibles:"
        docker images
    
    - name: "Mostar enviroment en linea de comandos"
      run: |
        echo "Variables de entorno:" ${{ toJson(env.database) }}
        echo "Variables de user:" ${{ toJson(env.user) }}
        echo "Variables de password:" ${{ toJson(env.password2) }}
    
    - name: "Mostrar variables de github"
      run: |
        echo "Variables de github:"
        echo "GITHUB_WORKSPACE: ${{ toJson(github.workspace) }}"
        echo "GITHUB_REPOSITORY: ${{ toJson(github.repository) }}"
        echo "GITHUB_REF: ${{ toJson(github.ref) }}"
        echo "GITHUB_ENV: ${{ toJson(github.env) }}"
        echo "GITHUB_ACTOR: ${{ toJson(github.actor) }}"
    
    - name: "Mostrar variables de SECRETS (hidden)"
      run: |
        echo "Variables de secrets:"
        echo "USERNAME: ${{ env.USERNAME }}"
        echo "PASSWORD: ${{ env.PASSWORD }}"
    
    - name: "Mostar variables de VARIABLES (show)"
      run: |
        echo "Variables de variables:"
        echo "language: ${{ env.language }}"
        echo "developer: ${{ env.developer }}"
    
    - name: "Acceder al repositorio"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Revisar archivo"
      run: |
        ls -l

      


