name: PRODUCCION_COREFINANCE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  proyecto: cacep
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}
  language: ${{ vars.LANGUAGE }}
  developer: ${{ vars.DESARROLLADOR }}

jobs:

  preview:
    runs-on: self-hosted
    steps:
      - name: Eliminar build redundante
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      
  build:
    needs: [preview]
    runs-on: self-hosted
    steps:
      - name: Create .env file
        run: |
          cat <<EOF > .env
          DATABASE=postgres
          USER=postgres
          PROYECTO=${{ env.proyecto }}
          USERNAME=${{ secrets.USERNAME }}
          PASSWORD=${{ secrets.PASSWORD }}
          EOF
        
  deploy:
    needs: [build]
    runs-on: self-hosted

    steps:
      - name: Verificar el repositorio
        uses: actions/checkout@v3
      
      - name: Copiar .env dentro de la carpeta var/www/html/
        run: sudo cp .env /var/www/html/${{ env.proyecto }}/

      - name: Desplegar dentro de la carpeta var/www/html
        run: |
          sudo rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.env.example' \
            --exclude='README.md' \
            "${{ github.workspace }}/" /var/www/html/${{ env.proyecto }}/
         
      - name: Listar archivos en /var/www/html/${{ env.proyecto }}/
        run: ls -la /var/www/html/${{ env.proyecto }}/

