name: Deploy to Apache folder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show working directory
        run: |
          echo "Working dir: ${{ github.workspace }}"
          ls -la ${{ github.workspace }}

      - name: Deploy to Apache folder
        run: |
          sudo rsync -av --delete "${{ github.workspace }}/" /var/www/html/cacep/
          sudo chown -R www-data:www-data /var/www/html/cacep/
