name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  database: postgres
  user: postgres
  password: postgres

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Mostrar imagnes"
      run: |
        echo "Imagenes disponibles:"
        docker images
    
    - name: "Mostar enviroment"
      run: |
        echo "Variables de entorno:" ${{ toJson(env.database) }}
        echo "Variables de user:" ${{ toJson(env.user) }}
        echo "Variables de password:" ${{ toJson(env.password) }}
        

