name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  database: postgres
  user: postgres
  password: postgres

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Mostrar imagnes"
      run: |
        echo "Imagenes disponibles:"
        docker images
    
    - name: "Mostar enviroment en linea de comandos"
      run: |
        echo "Variables de entorno:" ${{ toJson(env.database) }}
        echo "Variables de user:" ${{ toJson(env.user) }}
        echo "Variables de password:" ${{ toJson(env.password) }}
    
    - name: "Mostrar variables de github"
      run: |
        echo "Variables de github:"
        echo "GITHUB_WORKSPACE: ${{ toJson(github.workspace) }}"
        echo "GITHUB_REPOSITORY: ${{ toJson(github.repository) }}"
        echo "GITHUB_REF: ${{ toJson(github.ref) }}"
        echo "GITHUB_ENV: ${{ toJson(github.env) }}"


